.POSIX:
CC = c99
CFLAGS = -I../../ -I/home/camel/git/cauldron
LDLIBS = -lm

all: unsigned-division-by-constant

unsigned-division-by-constant: unsigned-division-by-constant.c

clean:
	rm -f unsigned-division-by-constant
