name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: apt-get update && apt-get install -y --no-install-recommends tcc
    - name: Run Tests
      run: cd tests && make
